### ISSUE TITLE
Undefined method slug after upgrading to 2.1.2

### ISSUE THREAD

**Issue by javinto** [refinery/refinerycms-news#138]
After upgrading RefineryCMS to v 2.1.1 and the news plugin to 2.1.2 i get an error when requesting the back-end. It tries to render the most recent activities after having added a news item:

```
Started GET "/refinery" for 127.0.0.1 at 2013-12-02 16:28:42 +0100
Processing by Refinery::Admin::DashboardController#index as HTML
........
`refinery_news_item_translations`.* FROM `refinery_news_item_translations` WHERE `refinery_news_item_translations`.`refinery_news_item_id` = 3
  Rendered /Users/javinto/.rvm/gems/ruby-2.0.0-p195/gems/refinerycms-dashboard-2.1.1/app/views/refinery/admin/dashboard/_recent_activity.html.erb (6.0ms)
  Rendered /Users/javinto/.rvm/gems/ruby-2.0.0-p195/gems/refinerycms-dashboard-2.1.1/app/views/refinery/admin/dashboard/_records.html.erb (9.0ms)
  Rendered /Users/javinto/.rvm/gems/ruby-2.0.0-p195/gems/refinerycms-dashboard-2.1.1/app/views/refinery/admin/dashboard/index.html.erb within layouts/refinery/admin (11.9ms)
Completed 500 Internal Server Error in 29.8ms

ActionView::Template::Error (undefined method `slug' for #<Refinery::News::Item::Translation:0x007f92c1573b30>):
    1: <div id='recent_activity'>
    2:   <h2><%= t('.latest_activity') %></h2>
    3:   <% if (activity = @recent_activity.collect { |a|
    4:           activity_message_for(a)
    5:         }.reject(&:blank?)).present? %>
    6:     <ul class='clickable'>
    7:     <% activity.each do |message| %>
  refinerycms-dashboard (2.1.1) app/helpers/refinery/admin/dashboard_helper.rb:13:in `eval'
```
